import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Floral Print Midi Dress",
    description:
      "Beautiful floral print midi dress perfect for spring and summer. Features a flattering A-line silhouette with a comfortable fit.",
    price: 29.99,
    originalPrice: 49.99,
    category: "women/clothing/dresses",
    image: "/floral-midi-dress-fashion.jpg",
    images: [
      "/floral-midi-dress-fashion-front.jpg",
      "/floral-midi-dress-fashion-back.jpg",
      "/floral-midi-dress-fashion-detail.jpg",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Pink", "White"],
    inStock: true,
    rating: 4.5,
    reviews: 128,
    tags: ["trending", "new arrival"],
  },
  {
    id: "2",
    name: "Oversized Graphic Tee",
    description: "Trendy oversized graphic t-shirt made from soft cotton blend. Perfect for casual everyday wear.",
    price: 15.99,
    originalPrice: 25.99,
    category: "women/clothing/tops",
    image: "/oversized-graphic-tee-fashion.jpg",
    images: ["/oversized-graphic-tee-fashion.jpg", "/oversized-tee-back-view.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    inStock: true,
    rating: 4.7,
    reviews: 342,
    tags: ["bestseller"],
  },
  {
    id: "3",
    name: "High Waist Wide Leg Jeans",
    description: "Classic high waist wide leg jeans with a vintage-inspired fit. Made from premium denim.",
    price: 39.99,
    category: "women/clothing/bottoms",
    image: "/high-waist-wide-leg-jeans.jpg",
    images: ["/high-waist-wide-leg-jeans.jpg", "/wide-leg-jeans-back.jpg"],
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Blue", "Black", "Light Blue"],
    inStock: true,
    rating: 4.3,
    reviews: 89,
    tags: [],
  },
  {
    id: "4",
    name: "Leather Crossbody Bag",
    description: "Elegant leather crossbody bag with adjustable strap. Perfect for everyday use.",
    price: 45.99,
    originalPrice: 79.99,
    category: "women/accessories/bags",
    image: "/leather-crossbody-bag.png",
    images: ["/leather-crossbody-bag.png", "/crossbody-bag-detail.jpg"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Tan"],
    inStock: true,
    rating: 4.8,
    reviews: 256,
    tags: ["trending"],
  },
  {
    id: "5",
    name: "Chunky Platform Sneakers",
    description: "Trendy chunky platform sneakers with a comfortable fit. Perfect for all-day wear.",
    price: 49.99,
    originalPrice: 69.99,
    category: "women/shoes/sneakers",
    image: "/chunky-platform-sneakers.jpg",
    images: ["/chunky-platform-sneakers.jpg", "/platform-sneakers-side-view.jpg"],
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["White", "Black", "Pink"],
    inStock: true,
    rating: 4.6,
    reviews: 198,
    tags: ["bestseller", "new arrival"],
  },
  {
    id: "6",
    name: "Cropped Blazer",
    description: "Stylish cropped blazer perfect for office or casual wear. Features a tailored fit.",
    price: 55.99,
    category: "women/clothing/outerwear",
    image: "/cropped-blazer-fashion.jpg",
    images: ["/cropped-blazer-fashion.jpg", "/blazer-back-view.jpg"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Beige", "Navy"],
    inStock: true,
    rating: 4.4,
    reviews: 67,
    tags: [],
  },
  {
    id: "7",
    name: "Gold Layered Necklace Set",
    description: "Delicate gold-plated layered necklace set. Includes three adjustable chains.",
    price: 12.99,
    originalPrice: 24.99,
    category: "women/accessories/jewelry",
    image: "/gold-layered-necklace.jpg",
    images: ["/gold-layered-necklace.jpg"],
    sizes: ["One Size"],
    colors: ["Gold", "Silver", "Rose Gold"],
    inStock: true,
    rating: 4.5,
    reviews: 412,
    tags: ["bestseller"],
  },
  {
    id: "8",
    name: "Ribbed Knit Tank Top",
    description: "Essential ribbed knit tank top in soft stretchy fabric. Perfect for layering.",
    price: 9.99,
    category: "women/clothing/tops",
    image: "/ribbed-knit-tank-top.jpg",
    images: ["/ribbed-knit-tank-top.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Beige", "Green"],
    inStock: true,
    rating: 4.6,
    reviews: 523,
    tags: ["bestseller"],
  },
  {
    id: "9",
    name: "Printed Mini Skirt",
    description: "Fun printed mini skirt with elastic waistband. Perfect for summer days.",
    price: 19.99,
    originalPrice: 32.99,
    category: "women/clothing/bottoms",
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Multi", "Black", "Blue"],
    inStock: true,
    rating: 4.2,
    reviews: 156,
    tags: ["new arrival"],
  },
  {
    id: "10",
    name: "Oversized Sunglasses",
    description: "Chic oversized sunglasses with UV protection. Includes protective case.",
    price: 14.99,
    category: "women/accessories/sunglasses",
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300"],
    sizes: ["One Size"],
    colors: ["Black", "Tortoise", "Pink"],
    inStock: true,
    rating: 4.7,
    reviews: 289,
    tags: ["trending"],
  },
  {
    id: "11",
    name: "Puffer Jacket",
    description: "Warm puffer jacket with hood. Water-resistant and perfect for cold weather.",
    price: 69.99,
    originalPrice: 99.99,
    category: "women/clothing/outerwear",
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Pink", "Beige"],
    inStock: true,
    rating: 4.8,
    reviews: 234,
    tags: ["bestseller", "trending"],
  },
  {
    id: "12",
    name: "Satin Slip Dress",
    description: "Elegant satin slip dress with adjustable straps. Perfect for special occasions.",
    price: 34.99,
    category: "women/clothing/dresses",
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Champagne", "Emerald"],
    inStock: true,
    rating: 4.6,
    reviews: 178,
    tags: ["new arrival"],
  },
  {
    id: "13",
    name: "Denim Jacket",
    description: "Classic denim jacket with a modern fit. Perfect for layering.",
    price: 54.99,
    originalPrice: 79.99,
    category: "women/clothing/outerwear",
    image: "/classic-denim-jacket.png",
    images: ["/denim-jacket-front.jpg", "/denim-jacket-back.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    inStock: true,
    rating: 4.5,
    reviews: 145,
    tags: ["bestseller"],
  },
  {
    id: "14",
    name: "Yoga Leggings",
    description: "High-performance yoga leggings with moisture-wicking fabric.",
    price: 24.99,
    category: "women/clothing/activewear",
    image: "/yoga-leggings.jpg",
    images: ["/yoga-leggings.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Gray"],
    inStock: true,
    rating: 4.7,
    reviews: 367,
    tags: ["trending"],
  },
  {
    id: "15",
    name: "Ankle Boots",
    description: "Stylish ankle boots with block heel. Perfect for any season.",
    price: 64.99,
    originalPrice: 89.99,
    category: "women/shoes/boots",
    image: "/stylish-ankle-boots.png",
    images: ["/ankle-boots-side.jpg", "/ankle-boots-detail.jpg"],
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Black", "Brown", "Tan"],
    inStock: true,
    rating: 4.6,
    reviews: 212,
    tags: ["new arrival"],
  },
  {
    id: "16",
    name: "Silk Scarf",
    description: "Luxurious silk scarf with elegant print. Multiple wearing options.",
    price: 18.99,
    category: "women/accessories/scarves",
    image: "/flowing-silk-scarf.png",
    images: ["/flowing-silk-scarf.png"],
    sizes: ["One Size"],
    colors: ["Multi", "Blue", "Pink", "Black"],
    inStock: true,
    rating: 4.4,
    reviews: 98,
    tags: [],
  },
  {
    id: "17",
    name: "Knit Cardigan",
    description: "Cozy knit cardigan perfect for layering. Features button closure.",
    price: 42.99,
    category: "women/clothing/sweaters",
    image: "/knit-cardigan.png",
    images: ["/knit-cardigan-open.jpg", "/knit-cardigan-closed.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Gray", "Black", "Cream"],
    inStock: true,
    rating: 4.8,
    reviews: 289,
    tags: ["bestseller", "trending"],
  },
  {
    id: "18",
    name: "Sports Bra",
    description: "High-support sports bra with adjustable straps. Ideal for workouts.",
    price: 19.99,
    category: "women/clothing/activewear",
    image: "/diverse-athletes-sports-bras.png",
    images: ["/diverse-athletes-sports-bras.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Pink", "Blue"],
    inStock: true,
    rating: 4.5,
    reviews: 431,
    tags: ["bestseller"],
  },
  {
    id: "19",
    name: "Canvas Tote Bag",
    description: "Eco-friendly canvas tote bag with inner pockets. Perfect for daily use.",
    price: 14.99,
    category: "women/accessories/bags",
    image: "/canvas-tote-bag.png",
    images: ["/canvas-tote-bag.png"],
    sizes: ["One Size"],
    colors: ["Natural", "Black", "Navy"],
    inStock: true,
    rating: 4.6,
    reviews: 187,
    tags: ["new arrival"],
  },
  {
    id: "20",
    name: "Wrap Midi Dress",
    description: "Flattering wrap midi dress with tie waist. Perfect for any occasion.",
    price: 38.99,
    originalPrice: 59.99,
    category: "women/clothing/dresses",
    image: "/wrap-midi-dress.jpg",
    images: ["/wrap-dress-front.jpg", "/wrap-dress-side.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Black", "Navy", "Floral"],
    inStock: true,
    rating: 4.7,
    reviews: 256,
    tags: ["trending"],
  },
  {
    id: "21",
    name: "Straw Hat",
    description: "Wide-brim straw hat with ribbon detail. Perfect for summer.",
    price: 22.99,
    category: "women/accessories/hats",
    image: "/straw-hat.png",
    images: ["/straw-hat.png"],
    sizes: ["One Size"],
    colors: ["Natural", "Black", "White"],
    inStock: true,
    rating: 4.4,
    reviews: 134,
    tags: ["new arrival"],
  },
  {
    id: "22",
    name: "Leather Belt",
    description: "Classic leather belt with gold buckle. Essential wardrobe staple.",
    price: 16.99,
    category: "women/accessories/belts",
    image: "/leather-belt.png",
    images: ["/leather-belt.png"],
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown", "Tan"],
    inStock: true,
    rating: 4.5,
    reviews: 223,
    tags: [],
  },
  {
    id: "23",
    name: "Cozy Sweater",
    description: "Soft and cozy oversized sweater. Perfect for lounging.",
    price: 34.99,
    category: "women/clothing/sweaters",
    image: "/cozy-sweater.jpg",
    images: ["/cozy-sweater.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Pink", "Gray", "Camel"],
    inStock: true,
    rating: 4.8,
    reviews: 412,
    tags: ["bestseller"],
  },
  {
    id: "24",
    name: "Running Shorts",
    description: "Lightweight running shorts with built-in liner. Moisture-wicking fabric.",
    price: 17.99,
    category: "women/clothing/activewear",
    image: "/athletic-running-shorts.png",
    images: ["/athletic-running-shorts.png"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Navy", "Pink", "Purple"],
    inStock: true,
    rating: 4.6,
    reviews: 298,
    tags: ["trending"],
  },
]

export const categories = ["Women", "Men", "Kids", "Beauty", "Home & Living", "Electronics"]
